# Generated by Django 5.0.6 on 2024-05-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("temperature", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("precipitation", models.CharField(max_length=100)),
            ],
        ),
    ]
