# Generated by Django 5.0.6 on 2024-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherrecord",
            name="date",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="weatherrecord",
            name="precipitation",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherrecord",
            name="temperature",
            field=models.FloatField(),
        ),
    ]
